services:
  db:
    image: postgres:16-alpine
    container_name: salary_db
    environment:
      POSTGRES_USER: salary_user
      POSTGRES_PASSWORD: salary_pass
      POSTGRES_DB: salary_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U salary_user -d salary_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
